---
#
# Ansible managed
#
repository:
  description: Install and configure roundcubemail on your system.
  homepage: https://buluma.github.io/
  topics: roundcubemail, ansible, molecule, tox, playbook
