---
  - name: Converge
    hosts: all
    become: true
    gather_facts: true

    vars_files: ../../vars/main.yml

    pre_tasks:
      - name: Update apt cache.
        apt: update_cache=yes cache_valid_time=600
        when: ansible_os_family == 'Debian'
        changed_when: false

    roles:
      - role: buluma.httpd
        httpd_vhosts:
          - name: docroot
            servername: roundcubemail.example.com
            documentroot: "{{ roundcubemail_install_directory }}"
      - role: buluma.roundcubemail
